# Absolute paths to sync (~ is expanded)
# Indented lines starting with ! are exclude patterns
# Destination in repo is derived by stripping $HOME/ prefix

~/.zshrc
~/.config/ghostty
~/.config/lazygit

~/.config/opencode
    !secrets
    !skills
    !node_modules

~/.config/yazi

~/.config/starship.toml

~/.config/zellij

~/.config/zed
    !prompts

# ~/.config/nvim
#   !.git
#   !.DS_Store
#   !lazy-lock.json

# ~/.config/karabiner
#   !automatic_backups
