gui:
  showRandomTip: false
  showBottomLine: false
  nerdFontsVersion: "3"
  theme:
    selectedLineBgColor:
      - "#393552"
git:
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never --true-color=always
      useConfig: false
customCommands:
  - key: "<c-g>"
    context: "files"
    command: "$HOME/.config/lazygit/deepseek-commit"
    description: "Generate commit message with DeepSeek"
    output: "terminal"
